version: 2
updates:
- package-ecosystem: bundler
  directory: "/api_server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: mimemagic
    versions:
    - 0.3.6
    - 0.3.7
    - 0.3.9
  - dependency-name: fugit
    versions:
    - 1.4.4
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: bootsnap
    versions:
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
    - 5.0.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: ffi
    versions:
    - 1.14.2
    - 1.15.0
  - dependency-name: nio4r
    versions:
    - 2.5.5
    - 2.5.7
  - dependency-name: minitest
    versions:
    - 5.14.4
  - dependency-name: i18n
    versions:
    - 1.8.9
  - dependency-name: puma
    versions:
    - 3.12.6
    - 5.2.0
    - 5.2.1
  - dependency-name: redis-namespace
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: tzinfo
    versions:
    - 1.2.9
  - dependency-name: rspec-support
    versions:
    - 3.9.4
  - dependency-name: rspec-core
    versions:
    - 3.9.3
  - dependency-name: rack
    versions:
    - 2.2.3
  - dependency-name: websocket-extensions
    versions:
    - 0.1.5
  - dependency-name: rspec-mocks
    versions:
    - 3.9.1
  - dependency-name: mysql2
    versions:
    - 0.5.3
  - dependency-name: rack-cors
    versions:
    - 1.1.1
  - dependency-name: rb-inotify
    versions:
    - 0.10.1
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nuxt
    versions:
    - 2.14.12
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: "@nuxtjs/axios"
    versions:
    - 5.12.5
    - 5.13.0
    - 5.13.1
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: gsap
    versions:
    - 3.6.0
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: bootstrap-vue
    versions:
    - 2.21.2
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: cross-env
    versions:
    - 7.0.3
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: node-sass
    versions:
    - 4.14.1
