version: 2
updates:
- package-ecosystem: bundler
  directory: "/api_server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
