version: '3'

volumes:
  api_database: {}
  redis_data: {}

services:
  default_log_rotate: &default_log_rotate
    image: busybox
    logging:
      options:
        max-size: 5m
        max-file: "5"
  api:
    <<: *default_log_rotate
    image: youwatana.be/api_server
    build:
      context: ./api_server
    env_file: .env
    environment:
      - RAILS_ENV=production
    volumes:
      - ./api_server:/usr/src/app
    networks:
      - default
    ports:
      - 13002:3000
  api_sidekiq:
    <<: *default_log_rotate
    image: youwatana.be/api_server
    env_file: .env
    environment:
      - RAILS_ENV=production
    volumes:
      - ./api_server:/usr/src/app
      - /dev/null:/usr/src/app/log/development.log
    command: bundle exec sidekiq
    networks:
      - default
  database:
    <<: *default_log_rotate
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - api_database:/var/lib/mysql
    ports:
      - 13306:3306
    networks:
      - default
  redis:
    <<: *default_log_rotate
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default
  nginx:
    <<: *default_log_rotate
    image: nginx:stable
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=api.youwatana.be
    ports:
      - 13000:80
    networks:
      - default

networks:
  default: {}
  shared:
    external: true
