version: '3'

volumes:
  api_database: {}
  redis_data: {}

services:
  api_server:
    image: youwatana.be/api_server
    build:
      context: ./api_server
    env_file: ./api_server/.env
    ports:
      - 13000:3000
    volumes:
      - ./api_server:/usr/src/app
  api_server_sidekiq:
    image: youwatana.be/api_server
    build:
      context: ./api_server
    env_file: ./api_server/.env
    volumes:
      - ./api_server:/usr/src/app
    command: bundle exec sidekiq
  frontend:
    image: youwatana.be/frontend
    build:
      context: frontend
    ports:
      - 13001:3000
  database:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - api_database:/var/lib/mysql
    ports:
      - 13306:3306
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
