default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>

development:
  <<: *default
  channel_prefix: action_cable_development

test:
  adapter: test

production:
  <<: *default
  channel_prefix: action_cable_production
