default: &default
  url: <%= ENV.fetch("REDIS_URL") %>

development:
  <<: *default
  namespace: redis_storage_development

test:
  <<: *default
  namespace: redis_storage_test

production:
  <<: *default
  namespace: redis_storage_production
