version: '3'

volumes:
  api_database: {}

services:
  database:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - api_database:/data
    ports:
      - 3306:3306
