version: '3'

volumes:
  api_database: {}

services:
  database:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: root
    volumes:
      - api_database:/data
  api_server:
    image: api_server
    build: .
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root@database:3306/
