version: '3'

volumes:
  api_database: {}
  redis_data: {}

services:
  api_server:
    image: api_server
    build: .
    env_file: .env
    ports:
      - 3000:3000
  database:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - api_database:/var/lib/mysql
    ports:
      - 13306:3306
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
